name: Bitcoin Trading Analysis

on:
  schedule:
    # Run at 6:00 AM, 12:00 PM, 6:00 PM, and 12:00 AM Bangkok time (UTC+7)
    - cron: '0 23,5,11,17 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-crypto-forecast:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      
      - name: Build crypto-forecast
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Run crypto-forecast
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          ./target/release/crypto-forecast > analysis.txt
          
      - name: Format date for issue title
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M UTC')" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Issue with Analysis
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const analysisText = fs.readFileSync('analysis.txt', 'utf8');
            const date = process.env.DATE;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Bitcoin Trading Analysis - ${date}`,
              body: analysisText,
              labels: ['analysis', 'automated']
            });
        env:
          DATE: ${{ steps.date.outputs.date }}