name: Bitcoin Trading Analysis

on:
  schedule:
    # Run at 6:00 AM and 6:00 PM Bangkok time (UTC+7)
    - cron: '0 23,11 * * *'
  workflow_dispatch:  # Allow manual triggering

# Only need read permissions for contents as we're no longer creating issues
permissions:
  contents: read

jobs:
  run-crypto-forecast:
    runs-on: ubuntu-latest
    environment: Main
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      
      - name: Build crypto-forecast
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Run crypto-forecast
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DATA_PROVIDER_API_KEY: ${{ secrets.DATA_PROVIDER_API_KEY }}
          API_BASE_URL: ${{ vars.API_BASE_URL }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          ./target/release/crypto-forecast telegram